name: Validate registered models
'on':
  push:
    branches-ignore:
     - gh-pages
    tags:
     - '*'
  schedule:
  - cron: 0 10 * * 1
jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        yggdrasil-version: [latest, dev]
      fail-fast: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      ###################################
      # CONDA SETUP
      ###################################
      - name: Set up MSVC Compiler on windows
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'
      - name: Set up miniconda test environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          miniforge-variant: Miniforge3
          miniforge-version: latest
          conda-remove-defaults: true
      - name: Check conda installation
        run: |
          conda info
          conda list
      - name: Install R (Windows)
        uses: r-lib/actions/setup-r@v2
        if: matrix.os == 'windows-latest'
      # - name: Install compilers using conda on Linux/Mac
      #   if: matrix.os != 'windows-latest'
      #   run: |
      #     conda install c-compiler cxx-compiler
      - name: Install Yggdrasil from conda-forge
        if: matrix.yggdrasil-version == 'latest'
        run: |
          conda install yggdrasil
      - name: Install development version of Yggdrasil
        if: matrix.yggdrasil-version == 'dev'
        run: |
          git clone --recurse-submodules https://github.com/cropsinsilico/yggdrasil.git
          cd yggdrasil
          git checkout topic/cache
          git submodule update --recursive
          python utils/setup_test_env.py install conda --for-development --always-yes --build-method direct
      - name: Install specific version of Yggdrasil from conda-forge
        if: matrix.yggdrasil-version != 'latest' && matrix.yggdrasil-version != 'dev'
        run: |
          conda install yggdrasil==${{ matrix.yggdrasil-version }} -y
      - name: Install R (Unix)
        if: matrix.os != 'windows-latest' && matrix.yggdrasil-version != 'dev'
        run:
          conda install yggdrasil.r
      - name: Check conda installation
        run: |
          conda info
          conda list

      ###################################
      # Validate
      ###################################
      - name: Check installed packages
        run: |
          conda list
          ygginfo --verbose
      - name: Validate models
        run: |
          python -m yggdrasil validate ./models --model-submission
